import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./providers";
import NavBar from "./Components/NavBar";
import { Toaster } from "react-hot-toast";
import Footer from "./Components/Footer";
import SideBae from "./Components/SideBae";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Test Performans",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <NavBar />
        <QueryProvider>
          <div className="container py-6">
            <div className="flex items-start gap-6   max-h-[20wh]">
              <SideBae />
              <main className="min-w-0  flex-1">{children}</main>
            </div>
          </div>
        </QueryProvider>
          <Toaster position="top-center" reverseOrder={false} />
        
        <Footer />
      </body>
    </html>
  );
}
